# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160914_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user_rec',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
