# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20160915_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskif',
            name='days',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
