# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_userskif_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskif',
            name='days',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
