# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20160915_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskif',
            name='last_works',
            field=models.CharField(default='[]', max_length=100000),
        ),
    ]
